---
name: My CI workflow

on:                             # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
  # To run workflows manually.  For example, you might want to update
  # your publications on a website every few months.
  workflow_dispatch:

jobs:

  lint:
    name: Lint the python package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6
      - name: Install and run ruff
        # v3.6.1
        uses: astral-sh/ruff-action@4919ec5cf1f49eff0871dbcea0da843445b837e6

  test:
    name: Test the python package
    needs: lint
    strategy:
      matrix:
        python-version: ["3.10", "3.14"]
        platform: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - python-version: "3.13"
            platform: "macos-15"
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6
      - name: Setup a specific version of python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install the package to run the tests
        run: pip install .[test]
      - name: Run the tests
        run: pytest -vv
